version: '3'
services:
  app1:
    build: ./app-1
  app2:
    build: ./app-2
  app3:
    build: ./app-3
  nginx:
    build: ./nginx 
    ports:
    - "80:80"
    depends_on:
      - app1
      - app2
      - app3