version: '3'
services:
  db:
    image: mysql:8.0.29
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: yair
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: chatapp
    volumes:
    - ./db:/docker-entrypoint-initdb.d/:ro
    - mysql-data:/var/lib/mysql
  app:
    restart: always
    build: ./app
    depends_on:
      - db
  nginx:
    build: ./nginx
    restart: always
    ports:
    - "80:80"
    depends_on:
      - app

volumes:
  mysql-data: